apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-api
  labels:
    app: cats-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cats-api
  template:
    metadata:
      labels:
        app: cats-api
    spec:
      containers:
        - name: cats-api
          image: vlad43590/cats-api:1.0.1
          ports:
            - containerPort: 8082
          env:
            - name: DATASOURCE_HOST
              value: 172.25.64.1
            - name: spring.mvc.servlet.path
              value: /cats-api
            - name: SPRING_ADMIN
              value: http://spring-admin/spring-admin
